source "https://rubygems.org"
gemspec

gem 'rake', '12.3.3'
gem 'kramdown-parser-gfm'
gem 'google_drive'
gem 'notion'
gem 'httplog'

gem "uuid", "~> 2.3"
gem "jekyll-tabs"
group :jekyll_plugins do
  gem "jekyll-difasia", '0.1.3', :path => '../data-processing/ruby/jekyll-difasia'
end

gem "colorize", "~> 0.8.1"

gem "git", "~> 1.8"
